# Generated by Django 5.2.1 on 2025-05-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TedarikciRegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedarikci_ad', models.CharField(max_length=150, unique=True)),
                ('temsilci_ad', models.CharField(max_length=40)),
                ('temsilci_soyad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('adres', models.TextField(unique=True)),
                ('cep_telefon', models.CharField(max_length=11, unique=True)),
                ('vergi_no', models.CharField(max_length=10, unique=True)),
                ('vergi_levhasi', models.FileField(upload_to='vergi_levhalari/')),
                ('verification_code', models.CharField(max_length=6)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TedarikciProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedarikci_ad', models.CharField(max_length=150)),
                ('temsilci_ad', models.CharField(max_length=40)),
                ('temsilci_soyad', models.CharField(max_length=50)),
                ('adres', models.TextField()),
                ('cep_telefon', models.CharField(max_length=11)),
                ('vergi_no', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tedarikci_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
