# Generated by Django 5.2.1 on 2025-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedarikci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tedarikciregistrationdata',
            name='tedarikci_ad',
            field=models.CharField(max_length=150),
        ),
    ]
