# Generated by Django 5.2.1 on 2025-05-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tedarikci', '0003_fooditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
