# Generated by Django 5.2.1 on 2025-05-28 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedarikci', '0004_delete_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('adet', 'Adet'), ('kilo', 'Kilo'), ('litre', 'Litre')], default='adet', max_length=10)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('iyi', 'İyi'), ('yaklasmis', 'Son kullanım tarihi yaklaşmış'), ('kotu', 'Kötü')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='tedarikci.tedarikciprofile')),
            ],
        ),
    ]
