# Generated by Django 5.2.1 on 2025-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedarikci', '0005_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='food_images/default_food.jpg', upload_to='food_images/'),
            preserve_default=False,
        ),
    ]
