# Generated by Django 5.2.1 on 2025-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedarikci', '0006_alter_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='allocation_status',
            field=models.CharField(choices=[('available', 'Başvurulabilir'), ('allocated', 'Tahsis Edildi')], default='available', max_length=20),
        ),
    ]
