# Generated by Django 5.2.1 on 2025-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationdata',
            name='adres',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='userregistrationdata',
            name='cep_telefon',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistrationdata',
            name='etebligat',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistrationdata',
            name='kutuk_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistrationdata',
            name='stk_ad',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
