# Generated by Django 5.2.1 on 2025-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0002_alter_userregistrationdata_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationdata',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistrationdata',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistrationdata',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
