# Generated by Django 5.2.1 on 2025-05-25 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0003_userregistrationdata_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_ad', models.CharField(max_length=150)),
                ('stk_temsilci_ad', models.CharField(max_length=40)),
                ('stk_temsilci_soyad', models.CharField(max_length=50)),
                ('adres', models.TextField()),
                ('cep_telefon', models.CharField(max_length=11)),
                ('stk_turu', models.CharField(max_length=10)),
                ('kutuk_no', models.CharField(blank=True, max_length=10, null=True)),
                ('etebligat', models.CharField(blank=True, max_length=19, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
