# Generated by Django 5.2.1 on 2025-05-31 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0004_profile'),
        ('tedarikci', '0006_alter_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tedarikci.fooditem')),
                ('stk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_applications', to='stk.profile')),
            ],
            options={
                'unique_together': {('stk_profile', 'food_item')},
            },
        ),
    ]
