# Generated by Django 5.2.1 on 2025-05-31 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0005_foodapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='FazlayizCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='courier_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='delivery_status',
            field=models.CharField(choices=[('pending_pickup', 'Alınmayı Bekliyor'), ('out_for_delivery', 'Yolda'), ('delivered_to_center', 'Merkeze Teslim Edildi'), ('tested_edible', 'Test Edildi - Yenilebilir'), ('tested_inedible', 'Test Edildi - Yenilemez')], default='pending_pickup', max_length=30),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='delivery_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_deliveries', to='stk.fazlayizcenter'),
        ),
    ]
