# Generated by Django 5.2.1 on 2025-06-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0006_fazlayizcenter_foodapplication_courier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('assigned', 'Atandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20),
        ),
    ]
