# Generated by Django 5.2.1 on 2025-06-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0007_alter_foodapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodapplication',
            name='delivery_center',
        ),
        migrations.RemoveField(
            model_name='foodapplication',
            name='courier_name',
        ),
        migrations.RemoveField(
            model_name='foodapplication',
            name='courier_phone',
        ),
        migrations.RemoveField(
            model_name='foodapplication',
            name='delivery_status',
        ),
        migrations.AlterField(
            model_name='foodapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='FazlayizCenter',
        ),
    ]
