# Generated by Django 5.2.1 on 2025-06-01 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0008_remove_foodapplication_delivery_center_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodapplication',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='delivery_status',
            field=models.CharField(choices=[('not_assigned', 'Kurye Atanmadı'), ('assigned_to_courier', 'Kuryeye Atandı'), ('picked_up_from_supplier', 'Tedarikçiden Alındı'), ('delivered_to_stk', 'STK ya Teslim Edildi')], default='not_assigned', max_length=30),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='stk_verification_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='supplier_verification_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
