# Generated by Django 5.2.1 on 2025-06-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0011_remove_profile_role_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='stk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='stk.profile'),
        ),
    ]
