# Generated by Django 5.2.1 on 2025-06-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0012_courier_is_available_courier_stk_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodapplication',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='foodapplication',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='foodapplication',
            name='stk_verification_code',
        ),
        migrations.RemoveField(
            model_name='foodapplication',
            name='supplier_verification_code',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
