# Generated by Django 5.2.1 on 2025-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0013_remove_foodapplication_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodapplication',
            name='final_destination',
            field=models.CharField(choices=[('awaiting_test_result', 'Test Sonucu Bekleniyor'), ('cold_storage', 'Soğuk Hava Deposu'), ('compost_center', 'Gübre Atık Merkezi'), ('disposal', 'İmha Edilecek')], default='awaiting_test_result', max_length=20),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='test_result',
            field=models.CharField(choices=[('awaiting_test', 'Test Bekleniyor'), ('edible', 'Yenilebilir'), ('inedible', 'Yenilemez')], default='awaiting_test', max_length=20),
        ),
    ]
