# Generated by Django 5.2.1 on 2025-06-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0014_foodapplication_final_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodapplication',
            name='final_destination',
            field=models.CharField(choices=[('awaiting_test_result', 'Test Sonucu Bekleniyor'), ('cold_storage', 'Soğuk Hava Deposu'), ('compost_center', 'Gübre Atık Merkezi'), ('disposal', 'İmha Edilecek')], default='awaiting_test_result', max_length=50),
        ),
    ]
