# Generated by Django 5.2.1 on 2025-06-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk', '0015_alter_foodapplication_final_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('awaiting_distribution', 'Dağıtım Bekliyor'), ('completed', 'Tamamlandı')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodapplication',
            name='test_result',
            field=models.CharField(choices=[('awaiting_test', 'Test Bekleniyor'), ('edible', 'Yenilebilir'), ('inedible', 'Yenilemez')], default='awaiting_test', max_length=50),
        ),
    ]
